# config.py
UNIVERSE_SIZE = 500
MONTE_CARLO_RUNS = 10000
DCF_WEIGHT = 0.40
RELATIVE_WEIGHT = 0.35
EARNINGS_WEIGHT = 0.25
RISK_FREE_RATE_DEFAULT = 0.045
UNDERVALUED_THRESHOLD = -1.5
OVERVALUED_THRESHOLD = 1.5
DB_PATH = "db/alphacraft.db"
FRED_API_KEY = "your_key_here"